version: '3.8'
services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "443:443/tcp"
    restart: unless-stopped
    networks:
      - chisel_network_internal
      - internet

  chisel_server:
    build: .
    container_name: chisel_server
    command: "/usr/local/bin/chisel server --port 8000 --reverse"
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - chisel_network_internal

  # job worker
  chisel_internal_client:
    build: .
    container_name: chisel_internal_client
    command: "/usr/local/bin/start_client.sh chisel_server 8000 8001"
    expose:
      - "8001"
    depends_on:
      - haproxy
    restart: unless-stopped
    networks:
      - chisel_network_internal

  # remote node
  chisel_external_client:
    build: .
    container_name: chisel_external_client
    command: "/usr/local/bin/start_client.sh haproxy 443 8002"
    expose:
      - "8002"
    depends_on:
      - haproxy
    restart: unless-stopped
    networks:
      - internet

networks:
  internet:
    driver: bridge
  chisel_network_internal:
    driver: bridge
